name: proyectoflutter
description: "Autos OG"

# Versión del SDK de Flutter y entorno
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.8.0
